XelAssistProfiles = {
    WARRIOR = { confidence = "medium", damage = {
        { "Execute", 980, "execute" }, { "Overpower", 930, "reactive" },
        { "Revenge", 920, "reactive" }, { "Bloodthirst", 850, "core" },
        { "Mortal Strike", 840, "core" }, { "Shield Slam", 830, "core" },
        { "Whirlwind", 760, "aoe" }, { "Slam", 620, "filler" },
        { "Heroic Strike", 500, "filler" },
    }, aoe = { { "Whirlwind", 900, "aoe" }, { "Cleave", 800, "aoe" } },
      defensive = { { "Shield Wall", 960, "emergency" }, { "Last Stand", 940, "emergency" } },
      interrupt = { { "Pummel", 1200, "interrupt" }, { "Shield Bash", 1190, "interrupt" } },
      buff = { { "Battle Shout", 800, "buff", selfOnly = true } } },
    PALADIN = { confidence = "medium", damage = {
        { "Judgement", 900, "debuff" }, { "Crusader Strike", 850, "core" },
        { "Holy Strike", 820, "core" }, { "Exorcism", 700, "conditional" },
    }, heal = { { "Holy Light", 900, "triage" }, { "Flash of Light", 850, "triage" } },
      defensive = { { "Divine Shield", 980, "emergency" }, { "Lay on Hands", 970, "emergency" } },
      interrupt = { { "Rebuke", 1200, "interrupt" } }, buff = {
        { "Blessing of Wisdom", 820, "buff", manaOnly = true },
        { "Blessing of Might", 800, "buff", nonMana = true } } },
    HUNTER = { confidence = "medium", damage = {
        { "Kill Command", 940, "pet" }, { "Aimed Shot", 850, "core" },
        { "Multi-Shot", 780, "aoe" }, { "Arcane Shot", 720, "filler" },
        { "Serpent Sting", 680, "debuff" }, { "Steady Shot", 620, "filler" },
        { "Shoot", 400, "resource recovery" },
    }, aoe = { { "Volley", 920, "ground", ground = true }, { "Multi-Shot", 880, "aoe" } },
      defensive = { { "Feign Death", 980, "threat" }, { "Deterrence", 950, "emergency" } },
      interrupt = { { "Counterattack", 1200, "interrupt" } }, buff = { { "Aspect of the Hawk", 800, "buff", selfOnly = true } } },
    ROGUE = { confidence = "high", damage = {
        { "Eviscerate", 900, "finisher", minCombo = 4 }, { "Rupture", 860, "finisher", minCombo = 4 },
        { "Riposte", 840, "reactive" }, { "Backstab", 740, "builder" },
        { "Sinister Strike", 700, "builder" },
    }, aoe = { { "Blade Flurry", 880, "aoe", cooldown = true }, { "Fan of Knives", 820, "aoe" } },
      defensive = { { "Evasion", 950, "emergency" }, { "Vanish", 930, "threat" } },
      interrupt = { { "Kick", 1200, "interrupt" } } },
    PRIEST = { confidence = "medium", damage = {
        { "Mind Blast", 850, "core" }, { "Shadow Word: Pain", 780, "debuff" },
        { "Mind Flay", 700, "filler" }, { "Smite", 620, "filler" }, { "Shoot", 400, "resource recovery" },
    }, heal = { { "Flash Heal", 950, "emergency triage" }, { "Greater Heal", 880, "triage" },
        { "Heal", 820, "efficient triage" }, { "Renew", 700, "maintenance" } },
      defensive = { { "Power Word: Shield", 960, "emergency" }, { "Fade", 920, "threat" } },
      interrupt = { { "Silence", 1200, "interrupt" } }, buff = { { "Power Word: Fortitude", 800, "buff" } } },
    SHAMAN = { confidence = "medium", damage = {
        { "Stormstrike", 900, "core" }, { "Earth Shock", 850, "core" },
        { "Flame Shock", 780, "debuff" }, { "Lightning Bolt", 650, "filler" },
    }, aoe = { { "Chain Lightning", 900, "aoe" }, { "Fire Nova Totem", 820, "aoe" } },
      heal = { { "Nature's Swiftness", 1100, "emergency", extra = true },
        { "Healing Wave", 900, "triage" }, { "Lesser Healing Wave", 880, "emergency triage" },
        { "Chain Heal", 820, "group triage" } },
      defensive = { { "Stoneclaw Totem", 900, "threat" } },
      interrupt = { { "Earth Shock", 1200, "interrupt" } }, buff = { { "Lightning Shield", 800, "buff", selfOnly = true } } },
    MAGE = { confidence = "high", damage = {
        { "Counterspell", 1200, "interrupt" }, { "Ice Barrier", 980, "defensive" },
        { "Frostbolt", 850, "core" }, { "Fireball", 700, "filler" },
        { "Shoot", 400, "resource recovery" },
    }, aoe = { { "Blizzard", 920, "ground", ground = true }, { "Cone of Cold", 860, "aoe" },
        { "Arcane Explosion", 780, "aoe" } },
      defensive = { { "Ice Block", 1000, "emergency" }, { "Ice Barrier", 950, "emergency" } },
      interrupt = { { "Counterspell", 1200, "interrupt" } },
      buff = { { "Arcane Intellect", 800, "buff", manaOnly = true },
        { "Frost Armor", 700, "buff", selfOnly = true } } },
    WARLOCK = { confidence = "medium", damage = {
        { "Shadowburn", 920, "execute", reagent = true }, { "Immolate", 820, "debuff" },
        { "Corruption", 780, "debuff" }, { "Shadow Bolt", 680, "filler" },
        { "Shoot", 400, "resource recovery" },
    }, aoe = { { "Rain of Fire", 900, "ground", ground = true }, { "Hellfire", 800, "aoe" } },
      defensive = { { "Death Coil", 960, "emergency" }, { "Healthstone", 900, "consumable", consumable = true } },
      interrupt = { { "Spell Lock", 1200, "interrupt", pet = true } }, buff = { { "Demon Armor", 800, "buff", selfOnly = true } } },
    DRUID = { confidence = "medium", damage = {
        { "Ferocious Bite", 900, "finisher", minCombo = 4 }, { "Rip", 850, "finisher", minCombo = 4 },
        { "Mangle", 820, "core" }, { "Shred", 760, "builder" }, { "Claw", 700, "builder" },
        { "Wrath", 650, "filler" },
    }, aoe = { { "Hurricane", 900, "ground", ground = true }, { "Swipe", 820, "aoe" } },
      heal = { { "Healing Touch", 900, "triage" }, { "Regrowth", 860, "emergency triage" },
        { "Rejuvenation", 720, "maintenance" } },
      defensive = { { "Barkskin", 950, "emergency" }, { "Frenzied Regeneration", 930, "emergency" } },
      interrupt = { { "Bash", 1200, "interrupt" } }, buff = { { "Mark of the Wild", 800, "buff" } } },
}
