-- Spell semantics, not rotations. The evaluator discovers known ranks from the
-- live spellbook and applies the same utility model to every class.
XelAssistKnowledge = {
    -- Shared utility
    ["Shoot"] = { kind = "damage", recovery = true, cast = 0, gcd = 0,
        ranged = true, weaponRanged = true, dynamicSchool = "equippedWand" },
    ["Attack"] = { kind = "damage", recovery = true, melee = true,
        whiteAttack = true, weaponHand = "main", cast = 0, gcd = 0 },

    -- Warrior
    ["Execute"] = { kind = "damage", execute = 20, melee = true, threat = 1.0 },
    ["Overpower"] = { kind = "damage", melee = true, reactive = true },
    ["Revenge"] = { kind = "damage", melee = true, reactive = true, threat = 1.6 },
    ["Bloodthirst"] = { kind = "damage", melee = true, threat = 1.0 },
    ["Mortal Strike"] = { kind = "damage", melee = true, threat = 1.0 },
    ["Shield Slam"] = { kind = "damage", melee = true, threat = 2.0 },
    ["Whirlwind"] = { kind = "damage", aoe = true, melee = true, threat = 1.0 },
    ["Slam"] = { kind = "damage", melee = true },
    ["Heroic Strike"] = { kind = "damage", melee = true, threat = 1.4 },
    ["Cleave"] = { kind = "damage", aoe = true, melee = true, threat = 1.2 },
    ["Rend"] = { kind = "dot", melee = true, bleed = true, ignoresArmor = true },
    ["Sunder Armor"] = { kind = "debuff", melee = true, threat = 2.0, stackable = 5,
        armorDebuff = true, modifierGroup = "majorArmor" },
    ["Thunder Clap"] = { kind = "debuff", aoe = true, melee = true, threat = 1.5 },
    ["Demoralizing Shout"] = { kind = "debuff", aoe = true, threat = 1.3 },
    ["Battle Shout"] = { kind = "buff", self = true },
    ["Pummel"] = { kind = "interrupt", melee = true },
    ["Shield Bash"] = { kind = "interrupt", melee = true, threat = 1.2 },
    ["Shield Wall"] = { kind = "defensive", cooldown = true },
    ["Last Stand"] = { kind = "defensive", cooldown = true },

    -- Paladin
    ["Holy Strike"] = { kind = "damage", melee = true, splashHeal = true, threat = 1.3 },
    ["Crusader Strike"] = { kind = "damage", melee = true },
    ["Judgement"] = { kind = "damage", debuff = true, dynamicSchool = "activeSeal" },
    ["Exorcism"] = { kind = "damage", ranged = true },
    ["Rebuke"] = { kind = "interrupt", melee = true },
    ["Consecration"] = { kind = "damage", aoe = true, threat = 1.4 },
    ["Holy Light"] = { kind = "heal" }, ["Flash of Light"] = { kind = "heal" },
    ["Holy Shock"] = { kind = "heal" },
    ["Divine Shield"] = { kind = "defensive", cooldown = true },
    ["Lay on Hands"] = { kind = "heal", emergency = true, cooldown = true },
    ["Blessing of Wisdom"] = { kind = "buff" }, ["Blessing of Might"] = { kind = "buff" },
    ["Blessing of Sanctuary"] = { kind = "buff" },

    -- Hunter
    ["Auto Shot"] = { kind = "damage", ranged = true, weaponRanged = true, ammunition = true, recovery = true },
    ["Steady Shot"] = { kind = "damage", ranged = true, weaponRanged = true, ammunition = true },
    ["Aimed Shot"] = { kind = "damage", ranged = true, weaponRanged = true, ammunition = true },
    ["Arcane Shot"] = { kind = "damage", ranged = true, weaponRanged = true, ammunition = true },
    ["Multi-Shot"] = { kind = "damage", ranged = true, weaponRanged = true, ammunition = true, aoe = true },
    ["Volley"] = { kind = "damage", ranged = true, aoe = true, ground = true },
    ["Serpent Sting"] = { kind = "dot", ranged = true }, ["Hunter's Mark"] = { kind = "debuff", ranged = true },
    ["Kill Command"] = { kind = "damage", pet = true, dynamicSchool = "petResult",
        damageActor = "pet" }, ["Raptor Strike"] = { kind = "damage", melee = true },
    ["Mongoose Bite"] = { kind = "damage", melee = true, reactive = true },
    ["Counterattack"] = { kind = "damage", melee = true, reactive = true },
    ["Lacerate"] = { kind = "dot", melee = true, bleed = true, ignoresArmor = true },
    ["Carve"] = { kind = "damage", melee = true, aoe = true },
    ["Immolation Trap"] = { kind = "dot", melee = true }, ["Explosive Trap"] = { kind = "damage", melee = true, aoe = true },
    ["Wing Clip"] = { kind = "debuff", melee = true },
    ["Aspect of the Hawk"] = { kind = "buff", self = true }, ["Aspect of the Wolf"] = { kind = "buff", self = true },
    ["Aspect of the Viper"] = { kind = "resource", self = true },
    ["Feign Death"] = { kind = "threatDrop" }, ["Deterrence"] = { kind = "defensive", cooldown = true },

    -- Rogue
    ["Sinister Strike"] = { kind = "builder", melee = true }, ["Backstab"] = { kind = "builder", melee = true, behind = true },
    ["Riposte"] = { kind = "damage", melee = true, reactive = true },
    ["Surprise Attack"] = { kind = "builder", melee = true, reactive = true },
    ["Noxious Assault"] = { kind = "builder", melee = true, mixedDamage = true,
        dynamicSchool = "weaponsAndPoisons" },
    ["Eviscerate"] = { kind = "damage", melee = true, combo = true },
    ["Rupture"] = { kind = "dot", melee = true, combo = true, bleed = true,
        ignoresArmor = true }, ["Slice and Dice"] = { kind = "buff", self = true, combo = true },
    ["Expose Armor"] = { kind = "debuff", melee = true, combo = true, armorDebuff = true,
        modifierGroup = "majorArmor" },
    ["Kick"] = { kind = "interrupt", melee = true }, ["Evasion"] = { kind = "defensive", cooldown = true },
    ["Vanish"] = { kind = "threatDrop", reagent = true, reagentName = "Flash Powder" },
    ["Blade Flurry"] = { kind = "damage", aoe = true, cooldown = true },
    ["Fan of Knives"] = { kind = "damage", aoe = true, melee = true },

    -- Priest
    ["Shadow Word: Pain"] = { kind = "dot", ranged = true }, ["Mind Blast"] = { kind = "damage", ranged = true, threat = 1.3 },
    ["Mind Flay"] = { kind = "damage", ranged = true, channel = true }, ["Smite"] = { kind = "damage", ranged = true },
    ["Holy Fire"] = { kind = "dot", ranged = true }, ["Flash Heal"] = { kind = "heal" },
    ["Greater Heal"] = { kind = "heal" }, ["Heal"] = { kind = "heal" }, ["Renew"] = { kind = "hot" },
    ["Prayer of Healing"] = { kind = "heal", aoe = true }, ["Power Word: Shield"] = { kind = "absorb" },
    ["Fade"] = { kind = "threatDrop" }, ["Silence"] = { kind = "interrupt", ranged = true },
    ["Power Word: Fortitude"] = { kind = "buff" },

    -- Shaman
    ["Stormstrike"] = { kind = "damage", melee = true },
    ["Lightning Strike"] = { kind = "damage", melee = true, mixedDamage = true,
        dynamicSchool = "damageComponents",
        damageComponents = {
            { school = 0, schoolMask = 1, mitigation = "armor", weaponMultiplier = 0.60 },
            { school = 3, schoolMask = 8, mitigation = "resistance", weaponMultiplier = 0.20 },
        } },
    ["Lightning Bolt"] = { kind = "damage", ranged = true }, ["Chain Lightning"] = { kind = "damage", ranged = true, aoe = true },
    ["Earth Shock"] = { kind = "damage", ranged = true, interrupt = true, threat = 1.4 },
    ["Flame Shock"] = { kind = "dot", ranged = true }, ["Molten Blast"] = { kind = "damage", ranged = true },
    ["Healing Wave"] = { kind = "heal" }, ["Lesser Healing Wave"] = { kind = "heal" },
    ["Chain Heal"] = { kind = "heal", aoe = true },
    ["Nature's Swiftness"] = { kind = "modifier", cooldown = true, nextInstant = true },
    ["Lightning Shield"] = { kind = "buff", self = true }, ["Water Shield"] = { kind = "resource", self = true },
    ["Fire Nova Totem"] = { kind = "damage", aoe = true }, ["Magma Totem"] = { kind = "damage", aoe = true },
    ["Stoneclaw Totem"] = { kind = "defensive", threat = 1.5, self = true },

    -- Mage
    ["Frostbolt"] = { kind = "damage", ranged = true, slow = true }, ["Fireball"] = { kind = "damage", ranged = true },
    ["Fire Blast"] = { kind = "damage", ranged = true }, ["Scorch"] = { kind = "damage", ranged = true, debuff = true },
    ["Pyroblast"] = { kind = "damage", ranged = true }, ["Arcane Missiles"] = { kind = "damage", ranged = true, channel = true },
    ["Arcane Surge"] = { kind = "damage", ranged = true, reactive = true }, ["Arcane Rupture"] = { kind = "debuff", ranged = true },
    ["Blizzard"] = { kind = "damage", ranged = true, aoe = true, ground = true, channel = true },
    ["Cone of Cold"] = { kind = "damage", aoe = true }, ["Arcane Explosion"] = { kind = "damage", aoe = true },
    ["Counterspell"] = { kind = "interrupt", ranged = true }, ["Ice Barrier"] = { kind = "absorb", self = true },
    ["Ice Block"] = { kind = "defensive", cooldown = true }, ["Arcane Intellect"] = { kind = "buff" },
    ["Icicles"] = { kind = "damage", ranged = true, reactive = true },
    ["Presence of Mind"] = { kind = "modifier", cooldown = true, nextInstant = true },
    ["Frost Armor"] = { kind = "buff", self = true },

    -- Warlock
    ["Shadow Bolt"] = { kind = "damage", ranged = true },
    ["Shadowburn"] = { kind = "damage", ranged = true, execute = 20,
        reagent = true, reagentName = "Soul Shard" },
    ["Immolate"] = { kind = "dot", ranged = true }, ["Corruption"] = { kind = "dot", ranged = true },
    ["Curse of Agony"] = { kind = "dot", ranged = true,
        exclusiveFamily = "warlockCurse" },
    ["Curse of Elements"] = { kind = "debuff", ranged = true, resistanceDebuff = true,
        modifierGroup = "curseElements", exclusiveFamily = "warlockCurse" },
    ["Curse of Shadow"] = { kind = "debuff", ranged = true, resistanceDebuff = true,
        modifierGroup = "curseShadow", exclusiveFamily = "warlockCurse" },
    ["Curse of Recklessness"] = { kind = "debuff", ranged = true, armorDebuff = true,
        modifierGroup = "curseArmor", exclusiveFamily = "warlockCurse" },
    ["Siphon Life"] = { kind = "dot", ranged = true, leech = true },
    ["Drain Life"] = { kind = "damage", ranged = true, channel = true, leech = true },
    ["Drain Soul"] = { kind = "damage", ranged = true, channel = true, recovery = true },
    ["Rain of Fire"] = { kind = "damage", ranged = true, aoe = true, ground = true, channel = true },
    ["Hellfire"] = { kind = "damage", aoe = true, channel = true },
    ["Death Coil"] = { kind = "damage", ranged = true, leech = true, cooldown = true },
    ["Spell Lock"] = { kind = "interrupt", ranged = true, pet = true }, ["Demon Armor"] = { kind = "buff", self = true },
    ["Summon Imp"] = { kind = "summon", summonRole = "support", summonFamily = "Imp" },
    ["Summon Voidwalker"] = { kind = "summon", summonRole = "tank", summonFamily = "Voidwalker",
        reagent = true, reagentName = "Soul Shard" },
    ["Summon Succubus"] = { kind = "summon", summonRole = "control", summonFamily = "Succubus",
        reagent = true, reagentName = "Soul Shard" },
    ["Summon Felhunter"] = { kind = "summon", summonRole = "interrupt", summonFamily = "Felhunter",
        reagent = true, reagentName = "Soul Shard" },

    -- Druid
    ["Shred"] = { kind = "builder", melee = true, behind = true }, ["Claw"] = { kind = "builder", melee = true },
    ["Mangle"] = { kind = "builder", melee = true }, ["Ferocious Bite"] = { kind = "damage", melee = true, combo = true },
    ["Rip"] = { kind = "dot", melee = true, combo = true, bleed = true,
        ignoresArmor = true }, ["Swipe"] = { kind = "damage", melee = true, aoe = true, threat = 1.3 },
    ["Maul"] = { kind = "damage", melee = true, threat = 1.6 }, ["Savage Bite"] = { kind = "damage", melee = true, threat = 2.0 },
    ["Wrath"] = { kind = "damage", ranged = true }, ["Starfire"] = { kind = "damage", ranged = true },
    ["Moonfire"] = { kind = "dot", ranged = true }, ["Insect Swarm"] = { kind = "dot", ranged = true },
    ["Hurricane"] = { kind = "damage", ranged = true, aoe = true, ground = true, channel = true },
    ["Healing Touch"] = { kind = "heal" }, ["Regrowth"] = { kind = "heal" }, ["Rejuvenation"] = { kind = "hot" },
    ["Faerie Fire"] = { kind = "debuff", ranged = true, armorDebuff = true,
        modifierGroup = "faerieArmor" },
    ["Faerie Fire (Feral)"] = { kind = "debuff", melee = true, armorDebuff = true,
        modifierGroup = "faerieArmor" },
    ["Barkskin"] = { kind = "defensive", cooldown = true }, ["Frenzied Regeneration"] = { kind = "heal", self = true },
    ["Bash"] = { kind = "interrupt", melee = true }, ["Mark of the Wild"] = { kind = "buff" },
}
